         cout << setw(13) << ' ' << "ÉÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍ»\n";
         cout << setw(13) << ' ' << "º        ³        ³                 ³                 º\n";
         cout << setw(13) << ' ' << "º        ³        ³                 ³                 º\n";
         cout << setw(13) << ' ' << "º                 ³                 ³        ÄÄÄÄÄÄÄÄÄ¶\n";
         cout << setw(13) << ' ' << "º                 ³         ÄÄÄÄÄÄÄÄ´                 º\n";
         cout << setw(13) << ' ' << "º                 ³                 ÃÄÄÄÄÄÄÄÄÄ        º\n";
         cout << setw(13) << ' ' << "º        ³        ³                 ³                 º\n";
         cout << setw(13) << ' ' << "º        ³        ³                 ³                 º\n";
         cout << setw(13) << ' ' << "ÈÍÍÍÍÍÍÍÍÏÍÍÍÍÑÍÍÍÏÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÍÏÍÍÍÑÍÍÍÍÍÍÍÍÍÍÍÍÍ¼\n";
         cout << setw(13) << ' ' << "              ³ Halley's Comet Software ³\n";
         cout << setw(13) << ' ' << "              ÀÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÙ\n\n";
         
         
         cout << "U64ASM was written by themind in order to complete Neon64.\n";
         cout << "anarko wrote the opcode list which this program uses.\n";
         cout << "Andreas Sterbenz wrote the checksum calculation routine.\n";
         cout << "Bung Enterprises Ltd. wrote most of the V64jr send routine.\n";
         cout << "Disch helped to debug the expression evaluator.\n\n";
         cout << "Version " << VERSION << " compiled " << CDATE << "\n\n";
         //cout << setw(3) << ' ' << "This software may be distributed freely, without charge, in any form which\n";
         //cout << setw(12) << ' ' <<"preserves credit to the author, Halley's Comet Software.\n\n";
         cout << setw(16) << ' ' << "Copyright (c) 2002-2003 Halley's Comet Software\n";
         cout << setw(30) << ' ' << "here.is/halleyscomet\n";
         cout << "\nThanks for keeping the N64 scene alive!";
